### ISSUE TITLE
Can't style chartist graphs with component styles

### ISSUE THREAD

**Issue by ajbeaven** [paradox41/angular2-chartist#13]
As the SVG elements that chartist renders don't get the `_ngcontent` attributes added to them, it's not possible to style these graphs [using component styles](https://angular.io/docs/ts/latest/guide/component-styles.html#!#appendix-1-inspecting-the-css-generated-in-emulated-view-encapsulation).

**Comment by paradox41** [comment]
I am not sure what the best way to handle this would be. I am not even sure I could do anything since I am not doing any of the rendering. 

Do you have any ideas?

**Comment by ajbeaven** [comment]
Sorry for the basic question, but can you please let me know how I might run the demo with .js source mappings enabled? `npm start` seems not to create them. After I've got that set up I can take a look to see if I can come up with something.

**Comment by paradox41** [comment]
You would have to add it to the webpack config here
https://github.com/paradox41/angular2-chartist/blob/master/webpack.config.js#L5

**Comment by paradox41** [comment]
Let me know if you find a solution
