### ISSUE TITLE
Animation support

### ISSUE THREAD

**Issue by doczoidberg** [paradox41/angular2-chartist#15]
I try to get run the [donut animation](http://gionkunz.github.io/chartist-js/examples.html#example-donut-animation) but getting errors:

`Chartist.Svg.Easing.easeOutQuint`  => `Chartist is not defined`

also `begin` does not exist on `animationDefinition['stroke-dashoffset']`

How can I solve the issue?

**Comment by paradox41** [comment]
> also begin does not exist on animationDefinition['stroke-dashoffset']

Sounds like typings issues? 

For the animation stuff, can you create a plunkr or something?

**Comment by victorcarvalhosp** [comment]
There's a way to make animated chartist with this angular2-chartist?

**Comment by victorcarvalhosp** [comment]
I'm stucked in the exact same thing... Anyone solve this?

Chartist.Svg.Easing.easeOutQuint => Chartist is not defined

also begin does not exist on animationDefinition['stroke-dashoffset']

Thanks!

**Comment by victorcarvalhosp** [comment]
Ater some time I figure it out, if someone wants an example:

`this.chart = {
				type: 'Pie',
				data:  {
					series: [this.disciplinePeriod.averages.allClass, this.subtractClass],
				},
				options: {
					donut: true,
					donutWidth: 10,
					showLabel: false
					//fullWidth: true,
					//width: '100%',
					//height: '100%'
				},
				events: {
					draw(data: any): void {
						console.log("EVENTSS");
						if (data.type === 'slice') {
							console.log(data);
							var pathLength = data.element._node.getTotalLength();

							data.element.attr({
								'stroke-dasharray': pathLength + 'px ' + pathLength + 'px'
							});

							var animationDefinition = {
								'stroke-dashoffset': {
									id: 'anim' + data.index,
									dur: 5000,
									from: -pathLength + 'px',
									to: '0px',
									//easing: "easeInSine",
									fill: 'freeze',
									//begin: 'anim' + (data.index - 1) + '.end';
								}
							};


							data.element.attr({
								'stroke-dashoffset': -pathLength + 'px'
							});
							console.log(data);
							data.element.animate(animationDefinition, false);
						}
					}
				}`
