### ISSUE TITLE
How can I make an animated chart?

### ISSUE THREAD

**Issue by victorcarvalhosp** [paradox41/angular2-chartist#34]
I want to do a chart like this:

http://gionkunz.github.io/chartist-js/examples.html#example-donut-animation

My chart is working fine, now I want to know how I can add this animation...

Thanks!

**Comment by paradox41** [comment]
You would need to hook into the `draw` event, just like in the example there. You can see it used [here](https://github.com/paradox41/angular2-chartist/blob/master/demo/demo.ts#L101-L105)
