### ISSUE TITLE
Chart only render ok after resize the screen

### ISSUE THREAD

**Issue by victorcarvalhosp** [paradox41/angular2-chartist#35]
I'm using angular2-chartist on a Ionic2 project and my chart only work after resize the screen, someone have any ideia what I'm doing wrong?

![chart-error](https://cloud.githubusercontent.com/assets/4266657/18418918/e72f0108-7825-11e6-897d-e73656bdd3d2.gif)

My code:

    `this.subtractClass = valorTotal - this.disciplinePeriod.averages.allClass;

			this.chart = {
				type: 'Pie',
				data:  {
					series: [this.disciplinePeriod.averages.allClass, this.subtractClass],
				},
				options: {
					donut: true,
					donutWidth: 10,
					showLabel: false
					//fullWidth: true,
					//width: '100%',
					//height: '100%'
				},
				events: {
					draw(data: any): void {
						console.log("EVENTSS");
						if (data.type === 'slice') {
							console.log(data);
							var pathLength = data.element._node.getTotalLength();

							data.element.attr({
								'stroke-dasharray': pathLength + 'px ' + pathLength + 'px'
							});

							var animationDefinition = {
								'stroke-dashoffset': {
									id: 'anim' + data.index,
									dur: 5000,
									from: -pathLength + 'px',
									to: '0px',
									//easing: "easeInSine",
									fill: 'freeze',
									//begin: 'anim' + (data.index - 1) + '.end';
								}
							};

							data.element.attr({
								'stroke-dashoffset': -pathLength + 'px'
							});
							console.log(data);
							data.element.animate(animationDefinition, false);
						}
					}
				}
			}

			this.subtractStudent = valorTotal - this.disciplinePeriod.averages.student;

			this.chartTurma = {
				type: 'Pie',
				data:  {
					series: [this.disciplinePeriod.averages.student, this.subtractStudent],
				},
				options: {
					donut: true,
					donutWidth: 30,
					showLabel: false,
					chartPadding: 15,
					className: 'oc-color',
					//fullWidth: true,
					//width: '100%',
					//height: '100%'
				},
				events: {
					draw(data: any): void {
						console.log("EVENTSS");
						if (data.type === 'slice') {
							console.log(data);
							var pathLength = data.element._node.getTotalLength();

							data.element.attr({
								'stroke-dasharray': pathLength + 'px ' + pathLength + 'px'
							});

							var animationDefinition = {
								'stroke-dashoffset': {
									id: 'anim' + data.index,
									dur: 5000,
									from: -pathLength + 'px',
									to: '0px',
									//easing: "easeInSine",
									fill: 'freeze',
									//begin: 'anim' + (data.index - 1) + '.end';
								}
							};

							data.element.attr({
								'stroke-dashoffset': -pathLength + 'px'
							});
							console.log(data);
							data.element.animate(animationDefinition, false);
						}
					}
				}
			}
`

I tried putting this code on constructor, and "onPageLoaded()" and got same results... Someone know what can I do?

**Comment by paradox41** [comment]
It might have to do with when the chart decides to take the size of its parent container. Can you try setting a height on the container at least?

**Comment by victorcarvalhosp** [comment]
Yes, look my html:

    `<ion-card>
        <ion-card-header>
            <ion-icon name="podium"></ion-icon>
            Ranking Outclass
        </ion-card-header>
        <ion-card-content>
            <div class="ct-square">

                <div class="stretched" >
                    <x-chartist id="class-average" class="stretched"
                                [data]="chart.data"
                                [type]="chart.type"
                                [options]="chart.options"
                                [responsiveOptions]="chart.responsiveOptions"
                                [events]="chart.events">
                    </x-chartist>
                </div>

                <div class="stretched" >
                    <x-chartist id="student-average" class="stretched"
                                [data]="chartTurma.data"
                                [type]="chartTurma.type"
                                [options]="chartTurma.options"
                                [responsiveOptions]="chartTurma.responsiveOptions"
                                [events]="chartTurma.events">

                    </x-chartist>
                </div>
            </div>
        </ion-card-content>

    </ion-card>
![chart-error-2](https://cloud.githubusercontent.com/assets/4266657/18419023/99a863ea-7828-11e6-879e-18a213b69ed5.png)

I think it's the exact same error that occurs here:
https://github.com/gionkunz/chartist-js/issues/119

Ther they update the chart and eerything works... But I can't find how to update on angular2-chartist... you think that can be the same thing? And if yes, can you give me an example of how to update the chart?

Thanks!
`

**Comment by paradox41** [comment]
Looks like he gives an example here: https://github.com/gionkunz/chartist-js/issues/119#issuecomment-68049172

You should have access to the chart in the same way for this component.

**Comment by victorcarvalhosp** [comment]
I'm trying but didn't work yet... You know some way to update without using jquery?

**Comment by paradox41** [comment]
Just use the native JS equivalent. `document.querySelectorAll`, `addEventListener`, etc

**Comment by victorcarvalhosp** [comment]
If I put `document.getElementById("student-average")__chartist__.update();` on my developers console it works.

But how I can call this on my .ts file?
I tried to put on "onPageLoaded()"
`onPageLoaded(){
		var el = document.getElementById("student-average");
		el.__chartist__.update();
}`

But i got this error:
Error TS2339: Property '__chartist__' does not exist on type 'HTMLElement'.

**Comment by victorcarvalhosp** [comment]
Can you give one example on how to update the chart?
with chartistjs I can do this way:
`setTimeout(function() {
  chart.update({
    labels: [1, 2, 3, 4, 5],
    series: [
      [5, 4, 3, 2, 1],
      [1, 2, 3, 4, 5]
    ]
  });
}, 5000);`

but this function update doesn't work on angular2-chartist...

**Comment by victorcarvalhosp** [comment]
The only way I've been able to fix this is adding a timeout:

    `onPageLoaded() {
		let valorTotal:number = 100;
		setTimeout(() => {
				this.subtractClass = valorTotal - this.disciplinePeriod.averages.allClass;
				this.createStudentChart();
			}
		}, 1000);

    private createStudentChart() {
		this.studentChart = {
			type: 'Pie',
			data: {
				series: [this.disciplinePeriod.averages.allClass, this.subtractClass],
			},
			options: {
				donut: true,
				donutWidth: 10,
				showLabel: false
			},
			events: {
				draw(data:any): void {
					if (data.type === 'slice') {
						console.log(data);
						var pathLength = data.element._node.getTotalLength();

						data.element.attr({
							'stroke-dasharray': pathLength + 'px ' + pathLength + 'px'
						});

						var animationDefinition = {
							'stroke-dashoffset': {
								id: 'anim' + data.index,
								dur: 4000,
								from: -pathLength + 'px',
								to: '0px',
								fill: 'freeze',
							}
						};


						data.element.attr({
							'stroke-dashoffset': -pathLength + 'px'
						});
						console.log(data);
						data.element.animate(animationDefinition, false);
					}
				}
			}
		}
	}`

**Comment by paradox41** [comment]
Thanks for the write up! Closing as resolved. Not quite ideal, but not sure of a better way either.
