### ISSUE TITLE
error importing ChartistModule

### ISSUE THREAD

**Issue by ritz078** [paradox41/angular2-chartist#39]
using `ChartistComponent` is working fine but if I try to import `ChartistModule`, there's error on console. I have to use chartist in multiple modules so can't import the component.

<img width="1348" alt="screen shot 2016-09-21 at 5 39 40 pm" src="https://cloud.githubusercontent.com/assets/5389035/18710397/ac05706c-8022-11e6-9072-b0622d19a5d7.png">

**Comment by paradox41** [comment]
I'll take a look, thanks for the report.

**Comment by ritz078** [comment]
its because `ChartComponent` is not exported from module. Adding 
```
exports: [
    ChartistComponent
  ]
```

to chartist.module fixes this.

**Comment by paradox41** [comment]
Great thank you! I'll probably fix this tonight, feel free to submit a PR if you need it urgently though.

**Comment by paradox41** [comment]
This should be available on 0.9.2. Thanks for the report.
