### ISSUE TITLE
How do I use chartist plugins ?

### ISSUE THREAD

**Issue by ritz078** [paradox41/angular2-chartist#40]
I want to use [chartist-plugin-tooltip](https://github.com/Globegitter/chartist-plugin-tooltip) but am not sure about how can I use it with this module.

**Comment by paradox41** [comment]
If you add `plugins` into the `options` block, it should just work.

**Comment by AlexanderKozhevin** [comment]
I'm having the same issue.
Ok, we just need to use standard syntax. Thanx fine.
But where can I add tooltip library? I'm using *angular-cli*.
If I add it in header, there gonna be error.
```
Uncaught ReferenceError: Chartist is not defined
    at chartist-plugin-tooltip.js:13
```
The same thing if I add it inside of a body. 
I guess this is pretty stupid question, but anyway.

**Comment by lukastl21** [comment]
Try to import Charist.
`import * as Chartist from 'chartist';`

**Comment by estomagordo** [comment]
In the deployed environment, I keep getting that Chartist.plugins is undefined. It does however work in a small sample file I run locally.

Does the order of imports of Chartist and the tooltip plugin matter, somehow?
