### ISSUE TITLE
A typo in the destroy method

### ISSUE THREAD

**Issue by user151** [paradox41/angular2-chartist#6]
Now it throws an error i.e. method not found
ngOnDestroy(): void {
    if (this.chart) {
      this.chart.**detatch**();
    }
  }

shouldn't it be:
 
ngOnDestroy(): void {
    if (this.chart) {
      this.chart.**detach**();
    }
  }

**Comment by paradox41** [comment]
Yes it should. Good catch!

**Comment by paradox41** [comment]
To follow up, it looks like an error in the [typings themselves](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/chartist/chartist.d.ts#L108):

```
ERROR in ./src/chartist.component.ts
(74,18): error TS2339: Property 'detach' does not exist on type 'IChartistPieChart | IChartistBarChart | IChartistLineChart'.
```

I will make a PR upstream to fix this as well.
