### ISSUE TITLE
How to configure interpolation?

### ISSUE THREAD

**Issue by Akkusativobjekt** [paradox41/angular2-chartist#89]
The documentation of Chartist states that the interpolation of a chart can be [configured](https://gionkunz.github.io/chartist-js/api-documentation.html#chartistinterpolation-method-none).

I found the Interface [IChartOptions](http://definitelytyped.org/docs/smoothie--smoothie/interfaces/smoothie.ichartoptions.html#interpolation) which defines different types/constants of the Interpolation and is exported as ChartOptions in the chartist.component file.

This knowledge has not been enough for me to implement it, I tried to set it with:
`      lineSmooth: {
        Interpolation :"step",
      }`
via the options.
This causes the error "can't assign to properties of (new Boolean(true)): not an object" and I guess I don't set it correctly.  But I think I'm close to the solution, because  lineSmooth seems to be a keyword.

Can someone provide me the correct way to do this?

**Comment by paradox41** [comment]
The example shows that option as being passed with the `options` object. Is that where you are including it?

Also, according to the docs, Interpolation is a function call:

```js
Chartist.Interpolation.none({
    fillHoles: false
 })
```

So are you importing Chartist and calling the appropriate function? The snippet you provide makes me think not. If you wanted step interpolation, it would like:

```js
Chartist.Interpolation.step({
    postpone: true,
    fillHoles: false
  })
```

**Comment by Akkusativobjekt** [comment]
First, thanks for the very fast reply!
Yes, I'm trying to set it via the option object like it is shown in the demo and It works for "simple" options like`axisX: {
        showLabel: false
      },`

As I now understands this has to be done via a function call. When I import chartist via
`import * as Chartist from 'chartist';` and set interpolation to none with your code snippet, nothing changes? Am I doing something wrong, again?

**Comment by paradox41** [comment]
Well, I am not sure what you might expect to see when you set interpolation like that, I guess it depends on the data you provide? But I would expect that to be correct.

**Comment by Akkusativobjekt** [comment]
I just did it wrong:

It now works if I import Chartist and add it to the options like : 

` lineSmooth: Chartist.Interpolation.step({
    postpone: true,
    fillHoles: false
})`

Thanks for your help!

**Comment by paradox41** [comment]
Good to hear. No problem.
